PATH=github.com/fuhsicloud/fuhsi-next/fuhsi-server/clients/ansible

version:
	go test -count=1 -v ${PATH}  -run=Test_Version

exec-shell:
	go test -count=1 -v ${PATH}  -run=Test_ExecShell

copy-file:
	go test -count=1 -v ${PATH}  -run=Test_CopyFile

